spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: Srinu19#
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

logging:
  level:
    syncqubits.ai.blog: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG